export const colors = {
  border: 'hsl(var(--border))',
  input: 'hsl(var(--input))',
  ring: 'hsl(var(--ring))',

  background: 'hsl(var(--background))',
  foreground: {
    DEFAULT: 'hsl(var(--foreground))',
    sharp: 'hsl(var(--foreground-sharp))',
    secondary: 'hsl(var(--foreground-secondary))',
    soft: 'hsl(var(--foreground-soft))',
    dim: 'hsl(var(--foreground-hint))',
    disabled: 'hsl(var(--foreground-disabled))',
  },
  accent: {
    DEFAULT: 'hsl(var(--accent))',
    foreground: 'hsl(var(--accent-foreground))',
  },

  card: {
    DEFAULT: 'hsl(var(--card))',
    foreground: 'hsl(var(--card-foreground))',
  },
  popover: {
    DEFAULT: 'hsl(var(--popover))',
    foreground: 'hsl(var(--popover-foreground))',
  },
  muted: {
    DEFAULT: 'hsl(var(--muted))',
    foreground: 'hsl(var(--muted-foreground))',
  },
  menu: {
    DEFAULT: 'hsl(var(--menu))',
    foreground: 'hsl(var(--menu-foreground))',
  },
  details: {
    DEFAULT: 'hsl(var(--details))',
    foreground: 'hsl(var(--details-foreground))',
  },

  // Colors
  default: {
    DEFAULT: 'hsl(var(--default))',
    foreground: 'hsl(var(--default-foreground))',
    sharp: 'hsl(var(--default-sharp))',
    'sharp-foreground': 'hsl(var(--default-sharp-foreground))',
    soft: 'hsl(var(--default-soft))',
    'soft-foreground': 'hsl(var(--default-soft-foreground))',
    dim: 'hsl(var(--default-dim))',
    'dim-foreground': 'hsl(var(--default-dim-foreground))',
  },
  primary: {
    DEFAULT: 'hsl(var(--primary))',
    foreground: 'hsl(var(--primary-foreground))',
    sharp: 'hsl(var(--primary-sharp))',
    'sharp-foreground': 'hsl(var(--primary-sharp-foreground))',
    soft: 'hsl(var(--primary-soft))',
    'soft-foreground': 'hsl(var(--primary-soft-foreground))',
    dim: 'hsl(var(--primary-dim))',
    'dim-foreground': 'hsl(var(--primary-dim-foreground))',
  },
  secondary: {
    DEFAULT: 'hsl(var(--secondary))',
    foreground: 'hsl(var(--secondary-foreground))',
    sharp: 'hsl(var(--secondary-sharp))',
    'sharp-foreground': 'hsl(var(--secondary-sharp-foreground))',
    soft: 'hsl(var(--secondary-soft))',
    'soft-foreground': 'hsl(var(--secondary-soft-foreground))',
    dim: 'hsl(var(--secondary-dim))',
    'dim-foreground': 'hsl(var(--secondary-dim-foreground))',
  },
  danger: {
    DEFAULT: 'hsl(var(--danger))',
    foreground: 'hsl(var(--danger-foreground))',
    sharp: 'hsl(var(--danger-sharp))',
    'sharp-foreground': 'hsl(var(--danger-sharp-foreground))',
    soft: 'hsl(var(--danger-soft))',
    'soft-foreground': 'hsl(var(--danger-soft-foreground))',
    dim: 'hsl(var(--danger-dim))',
    'dim-foreground': 'hsl(var(--danger-dim-foreground))',
  },
  warning: {
    DEFAULT: 'hsl(var(--warning))',
    foreground: 'hsl(var(--warning-foreground))',
    sharp: 'hsl(var(--warning-sharp))',
    'sharp-foreground': 'hsl(var(--warning-sharp-foreground))',
    soft: 'hsl(var(--warning-soft))',
    'soft-foreground': 'hsl(var(--warning-soft-foreground))',
    dim: 'hsl(var(--warning-dim))',
    'dim-foreground': 'hsl(var(--warning-dim-foreground))',
  },
  info: {
    DEFAULT: 'hsl(var(--info))',
    foreground: 'hsl(var(--info-foreground))',
    sharp: 'hsl(var(--info-sharp))',
    'sharp-foreground': 'hsl(var(--info-sharp-foreground))',
    soft: 'hsl(var(--info-soft))',
    'soft-foreground': 'hsl(var(--info-soft-foreground))',
    dim: 'hsl(var(--info-dim))',
    'dim-foreground': 'hsl(var(--info-dim-foreground))',
  },
  success: {
    DEFAULT: 'hsl(var(--success))',
    foreground: 'hsl(var(--success-foreground))',
    sharp: 'hsl(var(--success-sharp))',
    'sharp-foreground': 'hsl(var(--success-sharp-foreground))',
    soft: 'hsl(var(--success-soft))',
    'soft-foreground': 'hsl(var(--success-soft-foreground))',
    dim: 'hsl(var(--success-dim))',
    'dim-foreground': 'hsl(var(--success-dim-foreground))',
  },
  gem: {
    DEFAULT: 'hsl(var(--gem))',
    foreground: 'hsl(var(--gem-foreground))',
    sharp: 'hsl(var(--gem-sharp))',
    'sharp-foreground': 'hsl(var(--gem-sharp-foreground))',
    soft: 'hsl(var(--gem-soft))',
    'soft-foreground': 'hsl(var(--gem-soft-foreground))',
    dim: 'hsl(var(--gem-dim))',
    'dim-foreground': 'hsl(var(--gem-dim-foreground))',
  },
  precious: {
    DEFAULT: 'hsl(var(--precious))',
    foreground: 'hsl(var(--precious-foreground))',
    sharp: 'hsl(var(--precious-sharp))',
    'sharp-foreground': 'hsl(var(--precious-sharp-foreground))',
    soft: 'hsl(var(--precious-soft))',
    'soft-foreground': 'hsl(var(--precious-soft-foreground))',
    dim: 'hsl(var(--precious-dim))',
    'dim-foreground': 'hsl(var(--precious-dim-foreground))',
  },

  // Special
  day: {
    DEFAULT: 'hsl(var(--day))',
    foreground: 'hsl(var(--day-foreground))',
    sharp: 'hsl(var(--day-sharp))',
    'sharp-foreground': 'hsl(var(--day-sharp-foreground))',
    soft: 'hsl(var(--day-soft))',
    'soft-foreground': 'hsl(var(--day-soft-foreground))',
    dim: 'hsl(var(--day-dim))',
    'dim-foreground': 'hsl(var(--day-dim-foreground))',
  },
  week: {
    DEFAULT: 'hsl(var(--week))',
    foreground: 'hsl(var(--week-foreground))',
    sharp: 'hsl(var(--week-sharp))',
    'sharp-foreground': 'hsl(var(--week-sharp-foreground))',
    soft: 'hsl(var(--week-soft))',
    'soft-foreground': 'hsl(var(--week-soft-foreground))',
    dim: 'hsl(var(--week-dim))',
    'dim-foreground': 'hsl(var(--week-dim-foreground))',
  },
  month: {
    DEFAULT: 'hsl(var(--month))',
    foreground: 'hsl(var(--month-foreground))',
    sharp: 'hsl(var(--month-sharp))',
    'sharp-foreground': 'hsl(var(--month-sharp-foreground))',
    soft: 'hsl(var(--month-soft))',
    'soft-foreground': 'hsl(var(--month-soft-foreground))',
    dim: 'hsl(var(--month-dim))',
    'dim-foreground': 'hsl(var(--month-dim-foreground))',
  },
}
