create table "public"."routine" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "description" text
);


CREATE UNIQUE INDEX routine_pkey ON public.routine USING btree (id);

alter table "public"."routine" add constraint "routine_pkey" PRIMARY KEY using index "routine_pkey";


